# Generated by Django 3.0.6 on 2020-05-23 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0007_auto_20200522_1821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='current_branch',
            options={'verbose_name': 'Current Branch', 'verbose_name_plural': 'Current Branch'},
        ),
    ]
