# Generated by Django 3.0.6 on 2020-05-14 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0005_branches_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discrepancy', models.FloatField(blank=True, null=True)),
                ('actual_worth', models.FloatField(blank=True, null=True)),
                ('ordered_worth', models.FloatField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, default='', max_length=512)),
                ('payment_method', models.CharField(blank=True, default='', max_length=256)),
                ('is_paid', models.BooleanField()),
                ('date', models.DateField()),
                ('invoice_low', models.CharField(max_length=128)),
                ('invoice_high', models.CharField(max_length=128)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='location.Branches')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('retailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retailer_purchases', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
            },
        ),
        migrations.AddConstraint(
            model_name='purchases',
            constraint=models.UniqueConstraint(fields=('manager', 'branch', 'date'), name='unique purchase'),
        ),
    ]
