# Generated by Django 3.0.6 on 2020-05-20 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='invoice_image',
            field=models.FileField(blank=True, null=True, upload_to='purchases/invoices'),
        ),
        migrations.AddField(
            model_name='purchases',
            name='proof_of_payment',
            field=models.FileField(blank=True, null=True, upload_to='purchases/proofOfPayment'),
        ),
    ]
