# Generated by Django 3.0.6 on 2020-05-20 06:39

import adminApiModel.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20200520_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='purchases/invoices', validators=[adminApiModel.validators.file_size_15]),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='proof_of_payment',
            field=models.FileField(blank=True, null=True, upload_to='purchases/proofOfPayment', validators=[adminApiModel.validators.file_size_15]),
        ),
    ]
