# Generated by Django 3.0.6 on 2020-05-21 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_branches_manager'),
        ('stock', '0006_auto_20200520_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='location.Branches'),
        ),
    ]
