# Generated by Django 3.0.6 on 2020-05-21 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_auto_20200521_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchases',
            old_name='discrepancy',
            new_name='short_or_over',
        ),
    ]
