# Generated by Django 3.0.6 on 2020-05-22 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0009_auto_20200521_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('size', models.CharField(max_length=128)),
                ('price', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('date_start', models.DateField(editable=False)),
                ('product_id', models.CharField(max_length=128)),
                ('items_per_package', models.IntegerField()),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.AddConstraint(
            model_name='products',
            constraint=models.UniqueConstraint(fields=('manager', 'name', 'size', 'date_start'), name='unique product'),
        ),
    ]
