# Generated by Django 3.0.6 on 2020-05-23 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_auto_20200523_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchases',
            name='payment_method',
        ),
    ]
