# Generated by Django 3.0.6 on 2020-05-23 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_remove_purchases_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='stock.Purchase_Payment_Method'),
        ),
    ]
