# Generated by Django 3.0.6 on 2020-05-23 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0016_purchases_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
