# Generated by Django 3.0.6 on 2020-05-23 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0017_purchases_is_valid'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='purchases',
            name='unique purchase',
        ),
        migrations.AddConstraint(
            model_name='purchases',
            constraint=models.UniqueConstraint(condition=models.Q(is_valid=True), fields=('manager', 'branch', 'date'), name='unique purchase'),
        ),
    ]
