# Generated by Django 3.0.6 on 2020-05-23 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0018_auto_20200523_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_payment_method',
            name='manager',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_payment_methods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('manager', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='distributors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Distributor',
                'verbose_name_plural': 'Distributors',
            },
        ),
        migrations.AddConstraint(
            model_name='distributor',
            constraint=models.UniqueConstraint(fields=('manager', 'name'), name='unique distributor'),
        ),
    ]
