# Generated by Django 3.0.6 on 2020-05-23 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0019_auto_20200523_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='distributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='stock.Distributor'),
        ),
    ]
