# Generated by Django 3.0.6 on 2020-05-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0021_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='cost',
            field=models.FloatField(null=True),
        ),
    ]
