# Generated by Django 3.0.6 on 2020-05-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0022_products_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='date',
            field=models.DateField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
