# Generated by Django 3.0.6 on 2020-05-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0028_transactions_id_of_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='time',
            field=models.TimeField(blank=True, editable=False, null=True),
        ),
    ]
