# Generated by Django 3.0.6 on 2020-05-26 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0009_auto_20200523_1051'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0030_auto_20200526_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='id_of_product',
        ),
        migrations.AlterField(
            model_name='transactions',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='location.Branches'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='stock.Products'),
        ),
    ]
