# Generated by Django 3.0.6 on 2020-05-26 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0031_auto_20200526_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='stock.Products'),
        ),
    ]
