# Generated by Django 3.0.6 on 2020-05-26 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0033_auto_20200526_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='staff_id',
        ),
    ]
