# Generated by Django 3.0.6 on 2020-06-01 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0034_remove_transactions_staff_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='purchases',
            name='unique purchase',
        ),
    ]
