# Generated by Django 3.0.6 on 2020-06-01 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0036_remove_purchases_invoice_high'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchases',
            old_name='invoice_low',
            new_name='invoice_range',
        ),
    ]
