# Generated by Django 3.0.6 on 2020-06-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0037_auto_20200601_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='invoice_range',
            field=models.CharField(max_length=256),
        ),
    ]
