# Generated by Django 3.0.6 on 2020-06-01 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0038_auto_20200601_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchases',
            old_name='ordered_worth',
            new_name='invoice_worth',
        ),
    ]
