# Generated by Django 3.0.6 on 2020-06-01 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0039_auto_20200601_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchases',
            old_name='actual_worth',
            new_name='delivered_worth',
        ),
    ]
