# Generated by Django 3.0.6 on 2020-05-14 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0005_branches_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True)),
                ('discrepancy', models.FloatField(blank=True)),
                ('gross_sales', models.FloatField()),
                ('cash_on_caja', models.FloatField()),
                ('cash_for_deposit', models.FloatField()),
                ('remark', models.CharField(blank=True, default='', max_length=512)),
                ('was_deposited', models.BooleanField(default=False)),
                ('is_valid', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='location.Branches')),
                ('manager', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
            },
        ),
        migrations.AddConstraint(
            model_name='sales',
            constraint=models.UniqueConstraint(fields=('manager', 'branch', 'date', 'is_valid'), name='unique sale'),
        ),
    ]
