# Generated by Django 3.0.6 on 2020-05-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_banks_expense_methods_expense_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateField(),
        ),
    ]
