# Generated by Django 3.0.6 on 2020-05-19 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0005_branches_manager'),
        ('finance', '0004_auto_20200519_0708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('remark', models.CharField(blank=True, default='', max_length=512)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.Banks')),
                ('branch', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='location.Branches')),
                ('manager', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
                ('method_of_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Expense_Methods')),
                ('retailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retailer_expenses', to=settings.AUTH_USER_MODEL)),
                ('type_of_expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Expense_Types')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
            },
        ),
        migrations.AddConstraint(
            model_name='expenses',
            constraint=models.UniqueConstraint(fields=('manager', 'branch', 'date', 'type_of_expense'), name='unique expense'),
        ),
    ]
