# Generated by Django 3.0.6 on 2020-05-20 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_auto_20200519_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
