# Generated by Django 3.0.6 on 2020-05-20 06:39

import adminApiModel.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_auto_20200520_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='expenses', validators=[adminApiModel.validators.file_size_15]),
        ),
        migrations.AlterField(
            model_name='sales',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='sales', validators=[adminApiModel.validators.file_size_15]),
        ),
    ]
