# Generated by Django 3.0.6 on 2020-05-20 08:58

from django.db import migrations
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_sales_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='file',
            field=private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='expenses'),
        ),
    ]
