# Generated by Django 3.0.6 on 2020-05-20 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_expenses_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense_methods',
            options={'verbose_name': 'Expense Payment Method', 'verbose_name_plural': 'Expense Payment Methods'},
        ),
        migrations.AlterModelOptions(
            name='expenses',
            options={'verbose_name': 'Expense Report', 'verbose_name_plural': 'Expenses Report'},
        ),
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name': 'Sale Report', 'verbose_name_plural': 'Sales Report'},
        ),
    ]
