# Generated by Django 3.0.6 on 2020-05-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_auto_20200520_1016'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sales',
            name='unique sale',
        ),
        migrations.AddConstraint(
            model_name='sales',
            constraint=models.UniqueConstraint(fields=('manager', 'branch', 'date'), name='unique sale'),
        ),
    ]
