# Generated by Django 3.0.6 on 2020-05-21 11:01

from django.db import migrations
import finance.models
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_auto_20200521_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='file',
            field=private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=finance.models.Sales.user_directory_path),
        ),
    ]
