# Generated by Django 3.0.6 on 2020-05-21 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_auto_20200521_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='discrepancy',
            new_name='short_or_over',
        ),
    ]
