# Generated by Django 3.0.6 on 2020-05-23 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_auto_20200523_1051'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sales',
            name='unique sale',
        ),
        migrations.AddConstraint(
            model_name='sales',
            constraint=models.UniqueConstraint(condition=models.Q(is_valid=True), fields=('manager', 'branch', 'date'), name='unique sale'),
        ),
    ]
