# Generated by Django 3.0.6 on 2020-05-23 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_auto_20200523_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
