# Generated by Django 3.0.6 on 2020-05-23 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_expenses_is_valid'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='expenses',
            name='unique expense',
        ),
        migrations.AddConstraint(
            model_name='expenses',
            constraint=models.UniqueConstraint(condition=models.Q(is_valid=True), fields=('manager', 'branch', 'date', 'type_of_expense'), name='unique expense'),
        ),
    ]
