# Generated by Django 3.0.6 on 2020-05-24 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0009_auto_20200523_1051'),
        ('finance', '0020_auto_20200523_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='location.Branches'),
        ),
    ]
