# Generated by Django 3.0.6 on 2020-05-31 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import finance.models
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0023_auto_20200530_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('deposit', models.FloatField(blank=True, null=True)),
                ('withdraw', models.FloatField(blank=True, null=True)),
                ('update', models.FloatField(blank=True, null=True)),
                ('remark', models.CharField(default='', max_length=256)),
                ('check', models.BooleanField(default=False)),
                ('online', models.BooleanField(default=False)),
                ('image', private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=finance.models.Bank_Status.user_directory_path)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Banks')),
                ('expense_report', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_status', to='finance.Expenses')),
                ('manager', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_statuses', to=settings.AUTH_USER_MODEL)),
                ('sale_report', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_status', to='finance.Sales')),
            ],
            options={
                'verbose_name': 'Bank Status',
                'verbose_name_plural': 'Bank Statuses',
            },
        ),
    ]
