# Generated by Django 3.0.6 on 2020-05-31 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0025_auto_20200531_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_status',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
