# Generated by Django 3.0.6 on 2020-05-31 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0026_auto_20200531_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_status',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
