# Generated by Django 3.0.6 on 2020-06-01 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0027_auto_20200531_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
