# Generated by Django 3.0.6 on 2020-06-02 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0028_expenses_is_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='file',
            new_name='bill_stmt',
        ),
    ]
