# Generated by Django 3.0.6 on 2020-06-04 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0031_auto_20200602_0914'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='expenses',
            name='unique expense',
        ),
    ]
