# Generated by Django 3.0.6 on 2020-06-26 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0009_auto_20200523_1051'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0032_auto_20200604_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSales',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField()),
                ('short_or_over', models.FloatField(blank=True)),
                ('caja_minus_deposit', models.FloatField(blank=True, null=True)),
                ('gross_sales', models.FloatField()),
                ('cash_on_caja', models.FloatField()),
                ('cash_for_deposit', models.FloatField()),
                ('num_trxn', models.IntegerField(null=True)),
                ('num_cstmr', models.IntegerField(null=True)),
                ('num_rcpt', models.FloatField(null=True)),
                ('OR_nums', models.CharField(max_length=128, null=True)),
                ('total_disc', models.FloatField(null=True)),
                ('petty_cash', models.FloatField(null=True)),
                ('remark', models.CharField(blank=True, default='', max_length=512)),
                ('was_deposited', models.BooleanField(default=False)),
                ('is_valid', models.BooleanField(default=True)),
                ('file', models.TextField(blank=True, max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bank', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.Banks')),
                ('branch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='location.Branches')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('retailer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Sale Report',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
