# Generated by Django 3.0.6 on 2020-05-14 10:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0003_auto_20200514_1039'),
        ('staff', '0002_role_branches'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Role',
            new_name='Roles',
        ),
    ]
