# Generated by Django 3.0.6 on 2020-05-23 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_roles_is_assistant'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='sale_days',
            field=models.DateField(blank=True, null=True),
        ),
    ]
