# Generated by Django 3.0.6 on 2020-05-23 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_roles_sale_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='sale_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
