# Generated by Django 3.0.6 on 2020-05-23 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_auto_20200523_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='expense_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
