# Generated by Django 3.0.6 on 2020-05-23 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_roles_expense_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='purchase_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
