# Generated by Django 3.0.6 on 2020-05-23 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0009_auto_20200523_1051'),
        ('staff', '0009_roles_purchase_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='sale_staff',
            field=models.ManyToManyField(blank=True, related_name='sale_staffs', to='location.Branches'),
        ),
    ]
