# Generated by Django 3.0.6 on 2020-05-23 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_auto_20200523_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
