# Generated by Django 3.0.6 on 2020-05-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_roles_purchase_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='sale_can_validate',
            field=models.BooleanField(default=False),
        ),
    ]
