# Generated by Django 3.0.6 on 2020-05-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0016_roles_expense_can_validate'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='purchase_can_validate',
            field=models.BooleanField(default=False),
        ),
    ]
