# Generated by Django 3.0.6 on 2020-05-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0017_roles_purchase_can_validate'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='staff_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddConstraint(
            model_name='roles',
            constraint=models.UniqueConstraint(fields=('manager', 'staff_id'), name='unique staff id'),
        ),
    ]
