# Generated by Django 3.0.6 on 2020-06-05 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0018_auto_20200524_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hours_In',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours', models.FloatField()),
                ('day_type', models.CharField(choices=[('REG', 'Regular'), ('HD', 'Holiday')], default='REG', max_length=5)),
                ('manager', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_hours_in', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours_in', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Working Hours',
                'verbose_name_plural': 'Working Hours',
            },
        ),
    ]
