# Generated by Django 3.0.6 on 2020-06-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0019_hours_in'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='hours_in',
            constraint=models.UniqueConstraint(fields=('date', 'manager', 'staff'), name='unique hours in'),
        ),
    ]
