# Generated by Django 3.0.6 on 2020-06-05 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0020_auto_20200605_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bimonthly_In',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day', models.CharField(choices=[('8', '8'), ('23', '23')], max_length=5)),
                ('hrs_reg', models.FloatField()),
                ('tot_reg', models.FloatField()),
                ('hrs_hd', models.FloatField()),
                ('tot_hd', models.FloatField()),
                ('tot_comp', models.FloatField()),
                ('bene_a', models.FloatField()),
                ('bene_a_desc', models.CharField(max_length=128)),
                ('bene_b', models.FloatField()),
                ('bene_b_desc', models.CharField(max_length=128)),
                ('bene_c', models.FloatField()),
                ('bene_c_desc', models.CharField(max_length=128)),
                ('bene_d', models.FloatField()),
                ('bene_d_desc', models.CharField(max_length=128)),
                ('ded_a', models.FloatField()),
                ('ded_a_desc', models.CharField(max_length=128)),
                ('ded_b', models.FloatField()),
                ('ded_b_desc', models.CharField(max_length=128)),
                ('ded_c', models.FloatField()),
                ('ded_c_desc', models.CharField(max_length=128)),
                ('ded_d', models.FloatField()),
                ('ded_d_desc', models.CharField(max_length=128)),
                ('manager', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_bimontly_in', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bimontly_in', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Working BiMonthly',
                'verbose_name_plural': 'Working BiMonthly',
            },
        ),
        migrations.AddConstraint(
            model_name='bimonthly_in',
            constraint=models.UniqueConstraint(fields=('day', 'manager', 'staff', 'date'), name='unique bimonthly in'),
        ),
    ]
