# Generated by Django 3.0.6 on 2020-06-05 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0021_auto_20200605_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bimonthly_in',
            old_name='tot_hd',
            new_name='pay_hd',
        ),
        migrations.RenameField(
            model_name='bimonthly_in',
            old_name='tot_reg',
            new_name='pay_reg',
        ),
    ]
