# Generated by Django 3.0.6 on 2020-06-05 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0022_auto_20200605_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bimonthly_in',
            old_name='tot_comp',
            new_name='pay_tot',
        ),
    ]
