# Generated by Django 3.0.6 on 2020-06-05 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0023_auto_20200605_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimonthly_in',
            name='manager',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_bimonthly_in', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bimonthly_in',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bimonthly_in', to=settings.AUTH_USER_MODEL),
        ),
    ]
