# Generated by Django 3.0.6 on 2020-06-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0024_auto_20200605_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimonthly_in',
            name='bene_a',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bimonthly_in',
            name='bene_a_desc',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='bimonthly_in',
            name='bene_b',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bimonthly_in',
            name='bene_b_desc',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='bimonthly_in',
            name='bene_c',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bimonthly_in',
            name='bene_c_desc',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='bimonthly_in',
            name='bene_d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bimonthly_in',
            name='bene_d_desc',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='bimonthly_in',
            name='ded_a',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bimonthly_in',
            name='ded_a_desc',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='bimonthly_in',
            name='ded_b',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bimonthly_in',
            name='ded_b_desc',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='bimonthly_in',
            name='ded_c',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bimonthly_in',
            name='ded_c_desc',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='bimonthly_in',
            name='ded_d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bimonthly_in',
            name='ded_d_desc',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
