# Generated by Django 3.0.6 on 2020-06-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0025_auto_20200605_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimonthly_in',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
