# Generated by Django 3.0.6 on 2020-06-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0026_auto_20200605_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimonthly_in',
            name='hrs_hd',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bimonthly_in',
            name='hrs_reg',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bimonthly_in',
            name='pay_hd',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bimonthly_in',
            name='pay_reg',
            field=models.FloatField(default=0),
        ),
    ]
