# Generated by Django 3.0.6 on 2020-06-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0027_auto_20200605_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='hrly_rate',
            field=models.FloatField(null=True),
        ),
    ]
