# Generated by Django 3.0.6 on 2020-06-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0028_roles_hrly_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimonthly_in',
            name='date',
            field=models.DateField(),
        ),
    ]
