# Generated by Django 3.0.6 on 2020-06-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0029_auto_20200605_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimonthly_in',
            name='hrs_shd',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bimonthly_in',
            name='pay_shd',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='hours_in',
            name='day_type',
            field=models.CharField(choices=[('REG', 'Regular Day'), ('HD', 'Regular Holiday'), ('SHD', 'Special Holiday')], default='REG', max_length=5),
        ),
    ]
