# Generated by Django 3.0.6 on 2020-06-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0030_auto_20200605_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='rate_type',
            field=models.CharField(blank=True, choices=[('Min', 'Minimum Wage'), ('Pharm', 'Pharmacist Wage'), ('Man', 'Manager Wage')], default='', max_length=5),
        ),
    ]
