# Generated by Django 3.0.6 on 2020-06-07 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0031_roles_rate_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roles',
            name='rate_type',
        ),
    ]
