# Generated by Django 3.0.6 on 2020-06-07 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0032_remove_roles_rate_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Government_Benefits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(choices=[('SSS', 'SSS'), ('PH', 'Phil Health'), ('PI', 'Pag Ibig')], max_length=5)),
                ('total', models.FloatField(default=0)),
                ('staff_cont', models.FloatField(default=0)),
                ('mngr_cont', models.FloatField(default=0)),
                ('manager', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_government_benefits', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='government_benefits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('SAL', 'Salary Loan'), ('EME', 'Emergency Loan'), ('CAL', 'Calamity Loan')], max_length=5)),
                ('date_str', models.DateField()),
                ('date_end', models.DateField()),
                ('total', models.FloatField()),
                ('mnth_pay', models.FloatField()),
                ('total_paid', models.FloatField()),
                ('interest', models.FloatField()),
                ('is_paid', models.BooleanField(default=False)),
                ('is_valid', models.BooleanField(default=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='staff.Government_Benefits')),
                ('manager', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_government_loans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
