# Generated by Django 3.0.6 on 2020-06-07 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0033_government_benefits_loans'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='government_benefits',
            options={'verbose_name': 'Government Benefits', 'verbose_name_plural': 'Government Benefits'},
        ),
    ]
