# Generated by Django 3.0.6 on 2020-06-07 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0034_auto_20200607_1352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loans',
            options={'verbose_name': 'Loan', 'verbose_name_plural': 'Loans'},
        ),
    ]
