# Generated by Django 3.0.6 on 2020-06-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0035_auto_20200607_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimonthly_in',
            name='pay_ph',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bimonthly_in',
            name='pay_pi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bimonthly_in',
            name='pay_sss',
            field=models.BooleanField(default=False),
        ),
    ]
