# Generated by Django 3.0.6 on 2020-06-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0036_auto_20200607_1430'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='government_benefits',
            constraint=models.UniqueConstraint(fields=('manager', 'staff', 'institute'), name='unique government benefit'),
        ),
    ]
