# Generated by Django 3.0.6 on 2020-06-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0037_auto_20200607_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='allow_rate',
            field=models.FloatField(null=True),
        ),
    ]
