# Generated by Django 3.0.6 on 2020-06-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0038_roles_allow_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimonthly_in',
            name='extr_alw',
            field=models.FloatField(default=0),
        ),
    ]
