# Generated by Django 3.0.6 on 2020-06-18 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0039_bimonthly_in_extr_alw'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roles',
            old_name='allow_rate',
            new_name='hrly_allow',
        ),
    ]
