# Generated by Django 3.0.6 on 2020-06-26 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0042_branch_attendance'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='branch_attendance',
            constraint=models.UniqueConstraint(fields=('manager', 'branch', 'date'), name='unique branch attendance'),
        ),
    ]
