# Generated by Django 3.0.6 on 2020-07-06 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0045_auto_20200706_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='staff.Companies'),
        ),
    ]
