# Generated by Django 3.0.6 on 2020-07-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0047_auto_20200709_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='sale_change_deposit',
            field=models.BooleanField(default=False),
        ),
    ]
