# Generated by Django 3.0.6 on 2020-08-09 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0048_roles_sale_change_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalhours_in',
            name='day_type',
            field=models.CharField(choices=[('REG', 'Regular Day'), ('HD', 'Regular Holiday'), ('SHD', 'Special Holiday'), ('VL', 'Vacation Leave'), ('SL', 'Sick Leave')], default='REG', max_length=5),
        ),
        migrations.AlterField(
            model_name='hours_in',
            name='day_type',
            field=models.CharField(choices=[('REG', 'Regular Day'), ('HD', 'Regular Holiday'), ('SHD', 'Special Holiday'), ('VL', 'Vacation Leave'), ('SL', 'Sick Leave')], default='REG', max_length=5),
        ),
    ]
