# Generated by Django 3.0.6 on 2020-08-09 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0049_auto_20200809_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimonthly_in',
            name='hrs_sl',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bimonthly_in',
            name='hrs_vl',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bimonthly_in',
            name='pay_sl',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bimonthly_in',
            name='pay_vl',
            field=models.FloatField(default=0),
        ),
    ]
